# $MYAPP/annotator.yaml
apiVersion: transformers.example.co/v1
kind: App
metadata:
  name: example-app
  annotations:
    config.kubernetes.io/function: |
      wasip1:
        image: ghcr.io/koba1t/krm-fn-app:v0.0.3-wasm
spec:
  image: "ghcr.io/koba1t/go-http-server:v0.0.1"
  port: 8080
  domain: fnapp.x.k06.in
